
name: Check Loop
on: [push]
jobs:
  check_loop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile dorm example
        run: |
          g++ cpp_examples/dorm_example.cpp -o dorm_example
          echo "✅ dorm_example.cpp compiled"
