
name: Check Student
on: [push]
jobs:
  check_structs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Student struct
        run: |
          grep -q "struct Student" cpp_examples/student_example.cpp
          echo "✅ Student struct found"
